Merged PR 66968: Restrict scope if contact has placed orders on multiple stores
## What's being changed

The `getOrdersToProcess()` collection method. I've added a condition to restrict the join on store scope.

## Why it's being changed

This was a regression following [this commit](https://github.com/dotmailer/dotmailer-magento2-extension/commit/5747accc818242051e33d9c3cf8e8b3ca416223c). In the case that the same email had multiple rows in `email_contact`, each with a different contact id, we would get errors like:
```
dotdigital.ERROR: Error in order sync for website id: 2 ["Exception: Item (Dotdigitalgroup\\Email\\Model\\Order) with the same ID \"18\" already exists.
```

## How to review / test this change

- Connect website 1 to DD account 1
- Connect website 2 to DD account 2
- Place an order with the same email address on both websites
- Reset contacts and run customer sync
- You should now have 2 rows for the same email in `email_contact`, both with different contact ids
- Run order sync, see no errors > customer orders are synced to both Dotdigital accounts

Related work items: #307828