Merged PR 16658: Fix DI error from SenderResolver preference
## What's being changed

We're updating dependencies in some of our plugins and classes. `Dotdigitalgroup\Email\Model\Email\Template` is a non-injectable model because it represents a database entity - therefore `Dotdigitalgroup\Email\Model\Email\TemplateFactory` must be injected instead.

## Why it's being changed

Since introducing `DotdigitalSenderResolver`, and the `preference` in di.xml to use this class whenever Magento's `SenderResolverInterface` is requested, we started to notice errors after clearing cache.

Specifically:
```
Fatal error: Uncaught Error: Call to a member function getNext() on null in generated/code/Magento/User/Model/User/Interceptor.php
```

Because we were injecting a concrete class, we were trying to load all of its dependencies up front, before all the plugin code had been generated. By injecting a factory instead, Magento creates the correct class when it is required.

## How to review / test this change

- Test saving and changing template mappings
- Set up DDG SMTP
- Trigger transactional sends to ensure DotdigitalSenderResolver does its thing

## Notes

Test in 2.1, 2.2, 2.2.8, 2.3.

Related work items: #98717