Merged PR 66119: Restore multiple address headers for pre-2.4.8 Laminas messages
## What's being changed
- Added check to parse and add mail headers

## Why it's being changed
In Magento 2.4.7 messages are converted to symfony messages.
Sending messages to multiple recipients fails. We see this example message in the connector logs:
```
dotdigital.ERROR: TransportPlugin send exception: Expected response code "250/251/252" but got code "550", with message "550 Requested action not taken: mailbox unavailable". [] []
```

## How to review / test this change
- Use Magento 2.4.7
- Add the test script attached to `app/code/Dotdigitalgroup/Email/Test/SendMultipleRecipientsTest.php`
- Update email recipients in the `SendMultipleRecipientsTest.php`
- Remove the try catch at `app/code/Dotdigitalgroup/Email/Model/Mail/SymfonySmtpTransporter.php:62`
- Checkout develop
- Run `php -f app/code/Dotdigitalgroup/Email/Test/SendMultipleRecipientsTest.php`
- Observe the RFC error
- Checkout this branch
- Run `php -f app/code/Dotdigitalgroup/Email/Test/SendMultipleRecipientsTest.php`
- Observe the email is sent correctly without any errors

## Notes
[SendMultipleRecipientsTest.php (2).txt](https://dev.azure.com/dotdigital/b2ba4bc1-4a9a-48f7-a69a-5cf84134b7c4/_apis/git/repositories/cc22fc8a-89ce-4edf-ba9c-81a01b55e11a/pullRequests/66119/attachments/SendMultipleRecipientsTest.php%20%282%29.txt)

Related work items: #304037