Merged PR 63492: Make unit tests compatible with PHPUnit 10
## What's being changed

Our unit tests.

## Why it's being changed

Using `setMethods` and `withConsecutive` both now trigger errors in PHPUnit 10.5.

## How to review / test this change

- See a green build for unit tests against Magento 2.4.8-beta2

## Notes

I have marked the ImporterTest as skipped. For the time being I've not been able to figure out how to rewrite this test to prevent this error:
```
1) Dotdigitalgroup\Email\Test\Unit\Model\ImporterTest::testRegisterQueueReturnsTrueIfDataExists
Error: Call to undefined method MockObject_AbstractResource_883fce17::getIdFieldName()
```
The existing tests all test the `registerQueue` method, which is deprecated. Ideally, the Model\Importer class should only house functions relating to the model/entity, and any business logic should live elsewhere. Then we wouldn't be trying to unit test a subclass of `AbstractModel`.

Related work items: #291914